# Generated by Django 2.2.12 on 2021-02-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('ling', models.CharField(max_length=40)),
                ('tipe', models.CharField(max_length=40)),
                ('pembuat', models.CharField(max_length=40)),
                ('pemilik', models.CharField(max_length=40)),
            ],
        ),
    ]
