# Generated by Django 2.2.12 on 2021-02-10 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secureweb', '0002_web_kolom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=9)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='web',
            name='keamanan_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='secureweb.Kelompok'),
        ),
    ]
